### ISSUE TITLE
Navbar UI Issues

### ISSUE THREAD

**Issue by YupItsZac** [YupItsZac/FreeGeoAPI#40]
The navbar dropdowns look pretty ugly. I'm not a UI guy, so there is plenty of room for UI improvenments on this project. I'd like to include this in the next deployment if possible (on the 14th, I think). 

<img width="475" alt="bildschirmfoto 2016-01-07 um 17 54 48" src="https://cloud.githubusercontent.com/assets/6219957/12176455/c71476cc-b567-11e5-8e5c-d9a99cd8be39.png">

**Comment by georgeiosif** [comment]
Solved 

![12516202_895888417197907_470521663_n](https://cloud.githubusercontent.com/assets/11766982/12205612/7bd79260-b644-11e5-8162-0d4be0c74107.jpg)

**Comment by YupItsZac** [comment]
The changes you've made look good, @georgeiosif! We should also remove the hover background shading of the navbar items. Maybe just underline the active items? Thoughts?
