### ISSUE TITLE
Status page redesign

### ISSUE THREAD

**Issue by iosifache** [YupItsZac/FreeGeoAPI#43]
Status page have a lot of neon green and looks very ugly. I'd like to redesign it.

![capture](https://cloud.githubusercontent.com/assets/11766982/12207650/8f016ba2-b650-11e5-90a3-00159c320394.PNG)

**Comment by YupItsZac** [comment]
@georgeiosif, I think that is a good idea. What kind of design changes were you thinking? Just color, or layout, too?

**Comment by georgeiosif** [comment]
I like to do a new layout.

**Comment by YupItsZac** [comment]
Alright, cool. I think that would be good. I'll go ahead and add it to this milestone, so it will be deployed on the 14th (provided it's ready).

**Comment by YupItsZac** [comment]
Removing from V2 release to avoid delaying deployment.

**Comment by YupItsZac** [comment]
This was included in PR #53
